In [1]:
#the import packages
import requests
import pandas as pd
from pandas import json_normalize
import requests
import os
from pathlib import Path
from datetime import datetime, timezone,timedelta,time
from scipy import stats
import json
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
import sklearn as sklearn

In [2]:
pd.set_option("display.max_columns", None)

In [5]:
userInputData = loadDataFromFile("UserPrevious experiments-preprocessed")
timeSeriesData_BIG = loadDataFromFile("Data:Previous experiments-preprocessed")

/home/bob/Documents/Diploma project code/Diploma-Project/dataAnalysis and machine learning/data
Loaded 86 records from /home/bob/Documents/Diploma project code/Diploma-Project/dataAnalysis and machine learning/data/UserPrevious experiments-preprocessed.json
/home/bob/Documents/Diploma project code/Diploma-Project/dataAnalysis and machine learning/data
Loaded 208727 records from /home/bob/Documents/Diploma project code/Diploma-Project/dataAnalysis and machine learning/data/Data:Previous experiments-preprocessed.json

In [4]:
def loadDataFromFile(file_name):
    script_dir = Path().resolve().parent

    data_folder = script_dir / 'dataAnalysis and machine learning'/'data'
    print(data_folder)
    data_folder.mkdir(exist_ok=True)
    
    file_path = data_folder / (file_name + ".json")
    
    if file_path.exists():
        df = pd.read_json(file_path)
        print(f"Loaded {len(df)} records from {file_path}")
        return df
    else:
        print(f"File {file_path} does not exist.")
        return None

In [6]:
userInputData.head(20)

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,x axis,y axis,position of Id=0:BME680:breathVocEquivalent-x axis,position of Id=0:BME680:breathVocEquivalent-y axis,position of Id=1:BME680:breathVocEquivalent-x axis,position of Id=1:BME680:breathVocEquivalent-y axis,position of Id=2:BME680:breathVocEquivalent-x axis,position of Id=2:BME680:breathVocEquivalent-y axis,Id=1:BME680:breathVocEquivalent before insertion median,Id=1:BME680:breathVocEquivalent after insertion median,Id=1:BME680:breathVocEquivalent before insertion medianVOC standard scaled,Id=1:BME680:breathVocEquivalent after insertion medianVOC standard scaled,Id=2:BME680:breathVocEquivalent before insertion median,Id=2:BME680:breathVocEquivalent after insertion median,Id=2:BME680:breathVocEquivalent before insertion medianVOC standard scaled,Id=2:BME680:breathVocEquivalent after insertion medianVOC standard scaled,Id=0:BME680:breathVocEquivalent before insertion median,Id=0:BME680:breathVocEquivalent after insertion median,Id=0:BME680:breathVocEquivalent before insertion medianVOC standard scaled,Id=0:BME680:breathVocEquivalent after insertion medianVOC standard scaled
0,InsertingSourcePollutant,on,None,None,0.9,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.9,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,1751328000000,1751383639000,1751386482000,2843000,2543000.0,2543.0,300000.0,-0.95,1.1,NaN,NaN,-1.00,1.05,-0.30,1.05,1.509686,3.442836,-0.759440,0.189613,3.967107,9.312614,0.446996,3.071299,NaN,NaN,NaN,NaN
1,InsertingSourcePollutant,on,None,None,0.9,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.9,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,1751414400000,1751470970000,1751472290000,1320000,1000000.0,1000.0,320000.0,-0.95,1.1,NaN,NaN,-1.00,1.05,-0.30,1.05,0.528441,0.902638,-0.421601,1.483614,0.504590,0.759529,-0.543039,0.754978,NaN,NaN,NaN,NaN
2,InsertingSourcePollutant,on,None,None,0.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.9,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,1751500800000,1751545825000,1751546731000,906000,248000.0,248.0,658000.0,-0.95,1.6,NaN,NaN,-1.00,1.05,-0.30,1.05,2.089426,2.102715,-0.480229,-0.477821,4.116741,5.303647,-0.112933,0.102103,NaN,NaN,NaN,NaN
3,InsertingSourcePollutant,on,None,None,0.9,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,1751500800000,1751557900000,1751558350000,450000,88000.0,88.0,362000.0,-0.05,1.1,NaN,NaN,-1.00,1.05,-0.30,1.05,0.841969,0.945803,-0.584245,-0.570799,3.298144,5.734495,-0.266200,0.049277,NaN,NaN,NaN,NaN
4,InsertingSourcePollutant,on,None,None,1.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.3,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,1752019200000,1752087704000,1752089269000,1565000,1056000.0,1056.0,509000.0,-0.55,0.6,NaN,NaN,-1.00,1.05,-0.30,1.05,0.550905,0.968678,-0.941454,0.559800,0.813914,1.346549,0.003662,1.917668,NaN,NaN,NaN,NaN
5,InsertingSourcePollutant,None,None,None,0.9,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.7,None,None,2025-07-12 22:57:57,2025-07-12 22:31:25,2025-07-12 23:02:13,1752278400000,1752359643000,1752361331000,1688000,1435000.0,1435.0,253000.0,-0.15,1.1,NaN,NaN,-1.00,1.05,-0.30,1.05,2.173830,1.146073,-0.379294,-1.125457,3.012874,1.700728,0.229861,-0.722771,NaN,NaN,NaN,NaN
6,InsertingSourcePollutant,on,None,None,1.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.7,None,None,2025-07-14 19:40:37,2025-07-14 17:50:04,2025-07-14 19:48:32,1752451200000,1752517800000,1752520803000,3003000,NaN,NaN,NaN,-0.15,0.6,NaN,NaN,-1.00,1.05,-0.30,1.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 15:04:09,2025-07-19 14:59:47,2025-07-19 15:08:10,1752883200000,1752937189000,1752937689000,500000,261000.0,261.0,239000.0,-0.75,0.2,NaN,NaN,-0.65,-1.40,-0.75,1.10,1.563685,1.272217,1.066461,0.250089,0.793020,1.080155,-1.092091,-0.287856,NaN,NaN,NaN,NaN
8,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 15:17:10,2025-07-19 15:14:13,2025-07-19 15:21:23,1752883200000,1752938055000,1752938481000,426000,176000.0,176.0,250000.0,-0.75,0.2,NaN,NaN,-0.65,-1.40,-0.75,1.10,0.510188,0.754884,-0.885700,0.110029,0.556549,0.776737,-0.697046,0.198954,NaN,NaN,NaN,NaN
9,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 15:30:49,2025-07-19 15:25:07,2025-07-19 15:44:28,1752883200000,1752938709000,1752939867000,1158000,341000.0,341.0,817000.0,-0.75,0.2,NaN,NaN,-0.65,-1.40,-0.75,1.10,0.502524,1.898711,-1.033188,0.629860,0.506542,2.187190,-1.028403,0.973478,NaN,NaN,NaN,NaN
10,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 16:12:54,2025-07-19 16:04:22,2025-07-19 16:21:55,1752883200000,1752941064000,1752942114000,1050000,511000.0,511.0,539000.0,-0.75,0.2,NaN,NaN,-0.65,-1.40,-0.75,1.10,0.663598,2.064074,-0.658103,0.318007,0.720384,2.961681,-0.618524,0.943625,NaN,NaN,NaN,NaN
11,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 16:46:45,2025-07-19 16:36:03,2025-07-19 16:54:19,1752883200000,1752942964000,1752944058000,1094000,642000.0,642.0,452000.0,-0.75,0.2,NaN,NaN,-0.65,-1.40,-0.75,1.10,0.978361,1.621948,-0.524388,0.043128,0.957371,2.237204,-0.542897,0.585662,NaN,NaN,NaN,NaN
12,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 17:25:36,2025-07-19 17:05:51,2025-07-19 17:35:58,1752883200000,1752944752000,1752946557000,1805000,1185000.0,1185.0,620000.0,-0.75,0.2,NaN,NaN,-0.65,-1.40,-0.75,1.10,1.576052,2.531318,-0.318576,0.282196,1.338029,2.845891,-0.468270,0.480032,NaN,NaN,NaN,NaN
13,InsertingSourcePollutant,on,None,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 13:46:03,2025-07-20 13:36:41,2025-07-20 14:48:43,1752969600000,1753018602000,1753022921000,4319000,562000.0,562.0,3757000.0,-0.75,0.2,NaN,NaN,-0.65,-1.40,-0.75,1.10,0.560519,0.981377,-1.487203,-0.096548,0.561855,1.255179,-1.482786,0.808185,NaN,NaN,NaN,NaN
14,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 15:15:34,2025-07-20 15:04:15,2025-07-20 15:39:22,1752969600000,1753023857000,1753025960000,2103000,678000.0,678.0,1425000.0,-0.75,0.2,NaN,NaN,-0.65,-1.40,-0.75,1.10,0.453139,0.646429,-0.784237,-0.450725,0.511607,1.544939,-0.683353,1.099607,NaN,NaN,NaN,NaN
15,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,ανεμιστήρας,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 15:52:33,2025-07-20 15:47:36,2025-07-20 16:08:05,1752969600000,1753026458000,1753027683000,1225000,296000.0,296.0,929000.0,-0.75,0.2,NaN,NaN,-0.65,-1.40,-0.75,1.10,0.511630,2.391633,-0.968954,0.264101,0.515354,2.057345,-0.966512,0.044848,NaN,NaN,NaN,NaN
16,InsertingSourcePollutant,on,None,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 16:34:39,2025-07-20 16:20:42,2025-07-20 16:43:55,1752969600000,1753028444000,1753029834000,1390000,836000.0,836.0,554000.0,-0.75,0.2,NaN,NaN,-0.65,-1.40,-0.75,1.10,1.268598,1.420924,0.632336,1.281250,0.838628,1.043636,-1.199349,-0.326008,NaN,NaN,NaN,NaN
17,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 18:13:07,2025-07-20 18:04:08,2025-07-20 18:22:22,1752969600000,1753034650000,1753035740000,1090000,538000.0,538.0,552000.0,-0.75,0.2,NaN,NaN,-0.65,-1.40,-0.75,1.10,0.526276,1.042057,-0.889273,0.923913,0.521664,1.169276,-0.905486,1.371140,NaN,NaN,NaN,NaN
18,InsertingSourcePollutant,on,on,on,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 18:31:41,2025-07-20 18:29:19,2025-07-20 18:40:12,1752969600000,1753036161000,1753036811000,650000,141000.0,141.0,509000.0,-0.75,0.2,NaN,NaN,-0.65,-1.40,-0.75,1.10,0.499925,0.505668,-0.593855,-0.224049,0.500089,0.502533,-0.583308,-0.425943,NaN,NaN,NaN,NaN
19,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,ανεμιστήρας,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 18:47:26,2025-07-20 18:41:09,2025-07-20 19:00:09,1752969600000,1753036871000,1753038008000,1137000,376000.0,376.0,761000.0,-0.75,0.2,NaN,NaN,-0.65,-1.40,-0.75,1.10,0.524443,1.893610,-0.840343,0.078511,0.559183,2.265747,-0.817029,0.328254,NaN,NaN,NaN,NaN

In [7]:
# Convert back to timedelta
timeSeriesData_BIG['timestamp'] = pd.to_timedelta(timeSeriesData_BIG['timestamp'], unit='ms')

# Convert back to datetime

timeSeriesData_BIG ["datetime_timestamp"]= timeSeriesData_BIG['datetime_timestamp'].transform(
    lambda x: pd.to_datetime(x, unit='ms')
)
columns_datetime= [
       'date of experiment', 'actual timestamp StartingExperiment',
       'actual timestamp EndingExperiment', ]
columns_timedelta = ['time taken total',
       'timestamp InsertingSource timedelta',
       'time taken after insertion']

userInputData.loc[:,columns_datetime] = userInputData.loc[:,columns_datetime].apply(lambda x:pd.to_datetime(x, unit='ms'))
userInputData.loc[:,columns_timedelta] = userInputData.loc[:,columns_timedelta].apply(lambda x:pd.to_timedelta(x, unit='ms'))

/tmp/ipykernel_16896/3977477979.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '<DatetimeArray>
['2025-07-01 00:00:00', '2025-07-02 00:00:00', '2025-07-03 00:00:00',
 '2025-07-03 00:00:00', '2025-07-09 00:00:00', '2025-07-12 00:00:00',
 '2025-07-14 00:00:00', '2025-07-19 00:00:00', '2025-07-19 00:00:00',
 '2025-07-19 00:00:00', '2025-07-19 00:00:00', '2025-07-19 00:00:00',
 '2025-07-19 00:00:00', '2025-07-20 00:00:00', '2025-07-20 00:00:00',
 '2025-07-20 00:00:00', '2025-07-20 00:00:00', '2025-07-20 00:00:00',
 '2025-07-20 00:00:00', '2025-07-20 00:00:00', '2025-07-20 00:00:00',
 '2025-07-20 00:00:00', '2025-07-20 00:00:00', '2025-07-20 00:00:00',
 '2025-07-20 00:00:00', '2025-07-20 00:00:00', '2025-07-21 00:00:00',
 '2025-07-21 00:00:00', '2025-07-21 00:00:00', '2025-07-21 00:00:00',
 '2025-07-21 00:00:00', '2025-07-21 00:00:00', '2025-07-21 00:00:00',
 '2025-07-21 00:00:00', '2025-07-22 00:00:00', '2025-07-22 00:00:00',
 '2025-07-22 00:00:00', '2025-07-22 00:00:00', '2025-07-22 00:00:00',
 '2025-07-22 00:00:00', '2025-07-22 00:00:00', '2025-07-22 00:00:00',
 '2025-07-22 00:00:00', '2025-07-22 00:00:00', '2025-07-22 00:00:00',
 '2025-07-23 00:00:00', '2025-07-26 00:00:00', '2025-07-26 00:00:00',
 '2025-07-26 00:00:00', '2025-07-26 00:00:00', '2025-07-26 00:00:00',
 '2025-07-26 00:00:00', '2025-07-26 00:00:00', '2025-07-26 00:00:00',
 '2025-07-26 00:00:00', '2025-07-26 00:00:00', '2025-07-26 00:00:00',
 '2025-07-26 00:00:00', '2025-07-28 00:00:00', '2025-07-28 00:00:00',
 '2025-07-28 00:00:00', '2025-07-28 00:00:00', '2025-07-28 00:00:00',
 '2025-07-28 00:00:00', '2025-08-24 00:00:00', '2025-08-24 00:00:00',
 '2025-08-24 00:00:00', '2025-08-24 00:00:00', '2025-08-24 00:00:00',
 '2025-08-24 00:00:00', '2025-08-24 00:00:00', '2025-08-24 00:00:00',
 '2025-08-26 00:00:00', '2025-08-26 00:00:00', '2025-08-26 00:00:00',
 '2025-08-26 00:00:00', '2025-08-26 00:00:00', '2025-08-26 00:00:00',
 '2025-08-26 00:00:00', '2025-10-02 00:00:00', '2025-10-02 00:00:00',
 '2025-10-02 00:00:00', '2025-10-02 00:00:00', '2025-10-02 00:00:00',
 '2025-10-02 00:00:00', '2025-10-02 00:00:00']
Length: 86, dtype: datetime64[ns]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  userInputData.loc[:,columns_datetime] = userInputData.loc[:,columns_datetime].apply(lambda x:pd.to_datetime(x, unit='ms'))
/tmp/ipykernel_16896/3977477979.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '<DatetimeArray>
['2025-07-01 15:27:19', '2025-07-02 15:42:50', '2025-07-03 12:30:25',
 '2025-07-03 15:51:40', '2025-07-09 19:01:44', '2025-07-12 22:34:03',
 '2025-07-14 18:30:00', '2025-07-19 14:59:49', '2025-07-19 15:14:15',
 '2025-07-19 15:25:09', '2025-07-19 16:04:24', '2025-07-19 16:36:04',
 '2025-07-19 17:05:52', '2025-07-20 13:36:42', '2025-07-20 15:04:17',
 '2025-07-20 15:47:38', '2025-07-20 16:20:44', '2025-07-20 18:04:10',
 '2025-07-20 18:29:21', '2025-07-20 18:41:11', '2025-07-20 19:13:36',
 '2025-07-20 19:30:53', '2025-07-20 19:55:48', '2025-07-20 20:25:42',
 '2025-07-20 20:47:11', '2025-07-20 21:08:21', '2025-07-21 14:24:58',
 '2025-07-21 19:33:56', '2025-07-21 19:59:28', '2025-07-21 20:49:40',
 '2025-07-21 21:24:32', '2025-07-21 21:57:13', '2025-07-21 22:41:51',
 '2025-07-21 23:06:34', '2025-07-22 13:37:49', '2025-07-22 14:02:00',
 '2025-07-22 14:32:16', '2025-07-22 15:11:10', '2025-07-22 15:34:18',
 '2025-07-22 16:25:09', '2025-07-22 17:02:58', '2025-07-22 17:35:52',
 '2025-07-22 18:00:43', '2025-07-22 18:34:07', '2025-07-22 19:42:37',
 '2025-07-23 11:52:37', '2025-07-26 14:41:56', '2025-07-26 14:59:53',
 '2025-07-26 15:29:01', '2025-07-26 18:35:04', '2025-07-26 19:20:46',
 '2025-07-26 20:01:47', '2025-07-26 20:28:07', '2025-07-26 20:47:20',
 '2025-07-26 21:06:38', '2025-07-26 21:41:04', '2025-07-26 22:05:52',
 '2025-07-26 22:23:40', '2025-07-28 21:08:57', '2025-07-28 21:34:06',
 '2025-07-28 21:59:39', '2025-07-28 22:15:30', '2025-07-28 22:30:40',
 '2025-07-28 22:48:54', '2025-08-24 12:16:27', '2025-08-24 13:23:55',
 '2025-08-24 13:35:08', '2025-08-24 14:18:46', '2025-08-24 21:07:24',
 '2025-08-24 21:39:22', '2025-08-24 22:02:37', '2025-08-24 22:23:49',
 '2025-08-26 11:12:36', '2025-08-26 11:53:05', '2025-08-26 13:02:27',
 '2025-08-26 13:36:46', '2025-08-26 16:29:41', '2025-08-26 17:56:28',
 '2025-08-26 18:43:07', '2025-10-02 20:37:03', '2025-10-02 20:53:04',
 '2025-10-02 21:14:30', '2025-10-02 21:36:33', '2025-10-02 22:05:37',
 '2025-10-02 22:21:30', '2025-10-02 22:47:12']
Length: 86, dtype: datetime64[ns]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  userInputData.loc[:,columns_datetime] = userInputData.loc[:,columns_datetime].apply(lambda x:pd.to_datetime(x, unit='ms'))
/tmp/ipykernel_16896/3977477979.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '<DatetimeArray>
['2025-07-01 16:14:42', '2025-07-02 16:04:50', '2025-07-03 12:45:31',
 '2025-07-03 15:59:10', '2025-07-09 19:27:49', '2025-07-12 23:02:11',
 '2025-07-14 19:20:03', '2025-07-19 15:08:09', '2025-07-19 15:21:21',
 '2025-07-19 15:44:27', '2025-07-19 16:21:54', '2025-07-19 16:54:18',
 '2025-07-19 17:35:57', '2025-07-20 14:48:41', '2025-07-20 15:39:20',
 '2025-07-20 16:08:03', '2025-07-20 16:43:54', '2025-07-20 18:22:20',
 '2025-07-20 18:40:11', '2025-07-20 19:00:08', '2025-07-20 19:23:42',
 '2025-07-20 19:46:26', '2025-07-20 20:05:20', '2025-07-20 20:30:33',
 '2025-07-20 20:55:23', '2025-07-20 21:19:41', '2025-07-21 14:46:39',
 '2025-07-21 19:48:49', '2025-07-21 20:08:55', '2025-07-21 21:03:41',
 '2025-07-21 21:39:20', '2025-07-21 22:14:09', '2025-07-21 22:55:19',
 '2025-07-21 23:16:46', '2025-07-22 13:48:16', '2025-07-22 14:16:48',
 '2025-07-22 14:41:52', '2025-07-22 15:18:18', '2025-07-22 15:47:15',
 '2025-07-22 16:46:48', '2025-07-22 17:23:10', '2025-07-22 17:43:52',
 '2025-07-22 18:08:01', '2025-07-22 18:42:43', '2025-07-22 19:52:18',
 '2025-07-23 12:11:55', '2025-07-26 14:53:17', '2025-07-26 15:09:31',
 '2025-07-26 15:48:04', '2025-07-26 18:35:58', '2025-07-26 19:25:31',
 '2025-07-26 20:08:58', '2025-07-26 20:36:02', '2025-07-26 20:54:17',
 '2025-07-26 21:13:44', '2025-07-26 21:51:58', '2025-07-26 22:14:52',
 '2025-07-26 22:30:04', '2025-07-28 21:21:48', '2025-07-28 21:47:09',
 '2025-07-28 22:08:15', '2025-07-28 22:22:06', '2025-07-28 22:40:57',
 '2025-07-28 23:00:18', '2025-08-24 13:22:05', '2025-08-24 13:35:02',
 '2025-08-24 14:03:09', '2025-08-24 14:34:06', '2025-08-24 21:38:18',
 '2025-08-24 21:58:15', '2025-08-24 22:19:03', '2025-08-24 22:44:03',
 '2025-08-26 11:44:20', '2025-08-26 12:44:08', '2025-08-26 13:23:47',
 '2025-08-26 13:53:04', '2025-08-26 17:11:14', '2025-08-26 18:33:18',
 '2025-08-26 18:55:48', '2025-10-02 20:52:57', '2025-10-02 21:05:55',
 '2025-10-02 21:25:09', '2025-10-02 21:48:52', '2025-10-02 22:16:00',
 '2025-10-02 22:32:33', '2025-10-02 22:58:34']
Length: 86, dtype: datetime64[ns]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  userInputData.loc[:,columns_datetime] = userInputData.loc[:,columns_datetime].apply(lambda x:pd.to_datetime(x, unit='ms'))
/tmp/ipykernel_16896/3977477979.py:17: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '<TimedeltaArray>
['0 days 00:47:23', '0 days 00:22:00', '0 days 00:15:06', '0 days 00:07:30',
 '0 days 00:26:05', '0 days 00:28:08', '0 days 00:50:03', '0 days 00:08:20',
 '0 days 00:07:06', '0 days 00:19:18', '0 days 00:17:30', '0 days 00:18:14',
 '0 days 00:30:05', '0 days 01:11:59', '0 days 00:35:03', '0 days 00:20:25',
 '0 days 00:23:10', '0 days 00:18:10', '0 days 00:10:50', '0 days 00:18:57',
 '0 days 00:10:06', '0 days 00:15:33', '0 days 00:09:32', '0 days 00:04:51',
 '0 days 00:08:12', '0 days 00:11:20', '0 days 00:21:41', '0 days 00:14:53',
 '0 days 00:09:27', '0 days 00:14:01', '0 days 00:14:48', '0 days 00:16:56',
 '0 days 00:13:28', '0 days 00:10:12', '0 days 00:10:27', '0 days 00:14:48',
 '0 days 00:09:36', '0 days 00:07:08', '0 days 00:12:57', '0 days 00:21:39',
 '0 days 00:20:12', '0 days 00:08:00', '0 days 00:07:18', '0 days 00:08:36',
 '0 days 00:09:41', '0 days 00:19:18', '0 days 00:11:21', '0 days 00:09:38',
 '0 days 00:19:03', '0 days 00:00:54', '0 days 00:04:45', '0 days 00:07:11',
 '0 days 00:07:55', '0 days 00:06:57', '0 days 00:07:06', '0 days 00:10:54',
 '0 days 00:09:00', '0 days 00:06:24', '0 days 00:12:51', '0 days 00:13:03',
 '0 days 00:08:36', '0 days 00:06:36', '0 days 00:10:17', '0 days 00:11:24',
 '0 days 01:05:38', '0 days 00:11:07', '0 days 00:28:01', '0 days 00:15:20',
 '0 days 00:30:54', '0 days 00:18:53', '0 days 00:16:26', '0 days 00:20:14',
 '0 days 00:31:44', '0 days 00:51:03', '0 days 00:21:20', '0 days 00:16:18',
 '0 days 00:41:33', '0 days 00:36:50', '0 days 00:12:41', '0 days 00:15:54',
 '0 days 00:12:51', '0 days 00:10:39', '0 days 00:12:19', '0 days 00:10:23',
 '0 days 00:11:03', '0 days 00:11:22']
Length: 86, dtype: timedelta64[ns]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  userInputData.loc[:,columns_timedelta] = userInputData.loc[:,columns_timedelta].apply(lambda x:pd.to_timedelta(x, unit='ms'))
/tmp/ipykernel_16896/3977477979.py:17: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '<TimedeltaArray>
['0 days 00:42:23', '0 days 00:16:40', '0 days 00:04:08', '0 days 00:01:28',
 '0 days 00:17:36', '0 days 00:23:55',               NaT, '0 days 00:04:21',
 '0 days 00:02:56', '0 days 00:05:41', '0 days 00:08:31', '0 days 00:10:42',
 '0 days 00:19:45', '0 days 00:09:22', '0 days 00:11:18', '0 days 00:04:56',
 '0 days 00:13:56', '0 days 00:08:58', '0 days 00:02:21', '0 days 00:06:16',
 '0 days 00:02:16', '0 days 00:06:58', '0 days 00:04:09', '0 days 00:03:36',
 '0 days 00:01:33', '0 days 00:03:22', '0 days 00:07:38', '0 days 00:03:08',
 '0 days 00:03:16', '0 days 00:02:58', '0 days 00:06:39', '0 days 00:00:21',
 '0 days 00:02:35', '0 days 00:03:02', '0 days 00:03:19', '0 days 00:03:36',
 '0 days 00:03:23', '0 days 00:03:51', '0 days 00:07:35', '0 days 00:10:03',
 '0 days 00:16:42', '0 days 00:04:17', '0 days 00:02:26', '0 days 00:02:59',
 '0 days 00:05:59', '0 days 00:10:34', '0 days 00:05:14', '0 days 00:05:32',
 '0 days 00:11:42',               NaT, '0 days 00:02:11', '0 days 00:03:53',
 '0 days 00:04:26', '0 days 00:02:58', '0 days 00:03:15', '0 days 00:07:14',
 '0 days 00:04:56', '0 days 00:02:37', '0 days 00:08:17', '0 days 00:07:04',
 '0 days 00:01:56', '0 days 00:01:37', '0 days 00:03:57', '0 days 00:02:36',
 '0 days 00:06:40', '0 days 00:09:19', '0 days 00:02:42', '0 days 00:04:17',
 '0 days 00:00:10', '0 days 00:03:33', '0 days 00:03:13', '0 days 00:09:55',
 '0 days 00:00:27', '0 days 00:03:22', '0 days 00:07:04', '0 days 00:05:17',
 '0 days 00:19:31', '0 days 00:28:39', '0 days 00:03:35', '0 days 00:05:07',
 '0 days 00:02:53', '0 days 00:02:30', '0 days 00:02:33', '0 days 00:03:48',
 '0 days 00:03:52', '0 days 00:03:27']
Length: 86, dtype: timedelta64[ns]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  userInputData.loc[:,columns_timedelta] = userInputData.loc[:,columns_timedelta].apply(lambda x:pd.to_timedelta(x, unit='ms'))
/tmp/ipykernel_16896/3977477979.py:17: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '<TimedeltaArray>
['0 days 00:05:00', '0 days 00:05:20', '0 days 00:10:58', '0 days 00:06:02',
 '0 days 00:08:29', '0 days 00:04:13',               NaT, '0 days 00:03:59',
 '0 days 00:04:10', '0 days 00:13:37', '0 days 00:08:59', '0 days 00:07:32',
 '0 days 00:10:20', '0 days 01:02:37', '0 days 00:23:45', '0 days 00:15:29',
 '0 days 00:09:14', '0 days 00:09:12', '0 days 00:08:29', '0 days 00:12:41',
 '0 days 00:07:50', '0 days 00:08:35', '0 days 00:05:23', '0 days 00:01:15',
 '0 days 00:06:39', '0 days 00:07:58', '0 days 00:14:03', '0 days 00:11:45',
 '0 days 00:06:11', '0 days 00:11:03', '0 days 00:08:09', '0 days 00:16:35',
 '0 days 00:10:53', '0 days 00:07:10', '0 days 00:07:08', '0 days 00:11:12',
 '0 days 00:06:13', '0 days 00:03:17', '0 days 00:05:22', '0 days 00:11:36',
 '0 days 00:03:30', '0 days 00:03:43', '0 days 00:04:52', '0 days 00:05:37',
 '0 days 00:03:42', '0 days 00:08:44', '0 days 00:06:07', '0 days 00:04:06',
 '0 days 00:07:21',               NaT, '0 days 00:02:34', '0 days 00:03:18',
 '0 days 00:03:29', '0 days 00:03:59', '0 days 00:03:51', '0 days 00:03:40',
 '0 days 00:04:04', '0 days 00:03:47', '0 days 00:04:34', '0 days 00:05:59',
 '0 days 00:06:40', '0 days 00:04:59', '0 days 00:06:20', '0 days 00:08:48',
 '0 days 00:58:58', '0 days 00:01:48', '0 days 00:25:19', '0 days 00:11:03',
 '0 days 00:30:44', '0 days 00:15:20', '0 days 00:13:13', '0 days 00:10:19',
 '0 days 00:31:17', '0 days 00:47:41', '0 days 00:14:16', '0 days 00:11:01',
 '0 days 00:22:02', '0 days 00:08:11', '0 days 00:09:06', '0 days 00:10:47',
 '0 days 00:09:58', '0 days 00:08:09', '0 days 00:09:46', '0 days 00:06:35',
 '0 days 00:07:11', '0 days 00:07:55']
Length: 86, dtype: timedelta64[ns]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  userInputData.loc[:,columns_timedelta] = userInputData.loc[:,columns_timedelta].apply(lambda x:pd.to_timedelta(x, unit='ms'))

In [8]:
timeSeriesData_BIG

,keys,timestamp,sensors,VOC,after_insertion,original_value,datetime_timestamp,seconds,VOC rolling average,VOC gradient,VOC gradient cumsum,VOC standard scaled,VOC rolling average standard scaled
0,0,0 days 00:00:00,Id=1:BME680:breathVocEquivalent,1.472127,False,False,2025-07-01 15:27:19,0,1.477888,0.000436,0.000436,-0.777880,-0.775347
1,0,0 days 00:00:00,Id=2:BME680:breathVocEquivalent,1.430472,False,True,2025-07-01 15:27:19,0,1.460728,0.002113,0.002113,-0.798329,-0.783781
2,0,0 days 00:00:01,Id=1:BME680:breathVocEquivalent,1.468931,False,False,2025-07-01 15:27:20,1,1.478324,0.000326,0.000762,-0.779448,-0.775133
3,0,0 days 00:00:01,Id=2:BME680:breathVocEquivalent,1.434283,False,False,2025-07-01 15:27:20,1,1.462841,0.002084,0.004197,-0.796458,-0.782742
4,0,0 days 00:00:02,Id=1:BME680:breathVocEquivalent,1.469428,False,True,2025-07-01 15:27:21,2,1.478541,0.000201,0.000963,-0.779204,-0.775026
...,...,...,...,...,...,...,...,...,...,...,...,...,...
208722,85,0 days 00:11:21,Id=2:BME680:breathVocEquivalent,22.283267,True,False,2025-10-02 22:58:33,681,22.600279,-0.044358,11.678194,-0.286728,-0.273564
208723,85,0 days 00:11:21,Id=0:BME680:breathVocEquivalent,84.520770,True,True,2025-10-02 22:58:33,681,84.087691,0.127830,51.492018,2.388078,2.381402
208724,85,0 days 00:11:22,Id=1:BME680:breathVocEquivalent,23.429280,True,True,2025-10-02 22:58:34,682,23.313412,-0.045570,15.720697,-0.237475,-0.242772
208725,85,0 days 00:11:22,Id=2:BME680:breathVocEquivalent,22.354300,True,True,2025-10-02 22:58:34,682,22.556737,-0.043542,11.634652,-0.283675,-0.275444
208726,85,0 days 00:11:22,Id=0:BME680:breathVocEquivalent,84.101508,True,False,2025-10-02 22:58:34,682,84.199075,0.111384,51.603402,2.370060,2.386211

In [9]:
timeSeriesData_BIG.columns

Index(['keys', 'timestamp', 'sensors', 'VOC', 'after_insertion',
       'original_value', 'datetime_timestamp', 'seconds',
       'VOC rolling average', 'VOC gradient', 'VOC gradient cumsum',
       'VOC standard scaled', 'VOC rolling average standard scaled'],
      dtype='object')

In [10]:
#timeSeriesData_BIG = timeSeriesData_BIG.drop(['VOC standard scaled', 'VOC gradient'],axis=1)

In [11]:
#timeSeriesData_BIG = timeSeriesData_BIG.set_index("seconds")

In [12]:
timeSeriesData_BIG

,keys,timestamp,sensors,VOC,after_insertion,original_value,datetime_timestamp,VOC rolling average,VOC gradient,VOC gradient cumsum,VOC standard scaled,VOC rolling average standard scaled
seconds,,,,,,,,,,,,
0,0,0 days 00:00:00,Id=1:BME680:breathVocEquivalent,1.472127,False,False,2025-07-01 15:27:19,1.477888,0.000436,0.000436,-0.777880,-0.775347
0,0,0 days 00:00:00,Id=2:BME680:breathVocEquivalent,1.430472,False,True,2025-07-01 15:27:19,1.460728,0.002113,0.002113,-0.798329,-0.783781
1,0,0 days 00:00:01,Id=1:BME680:breathVocEquivalent,1.468931,False,False,2025-07-01 15:27:20,1.478324,0.000326,0.000762,-0.779448,-0.775133
1,0,0 days 00:00:01,Id=2:BME680:breathVocEquivalent,1.434283,False,False,2025-07-01 15:27:20,1.462841,0.002084,0.004197,-0.796458,-0.782742
2,0,0 days 00:00:02,Id=1:BME680:breathVocEquivalent,1.469428,False,True,2025-07-01 15:27:21,1.478541,0.000201,0.000963,-0.779204,-0.775026
...,...,...,...,...,...,...,...,...,...,...,...,...
681,85,0 days 00:11:21,Id=2:BME680:breathVocEquivalent,22.283267,True,False,2025-10-02 22:58:33,22.600279,-0.044358,11.678194,-0.286728,-0.273564
681,85,0 days 00:11:21,Id=0:BME680:breathVocEquivalent,84.520770,True,True,2025-10-02 22:58:33,84.087691,0.127830,51.492018,2.388078,2.381402
682,85,0 days 00:11:22,Id=1:BME680:breathVocEquivalent,23.429280,True,True,2025-10-02 22:58:34,23.313412,-0.045570,15.720697,-0.237475,-0.242772
682,85,0 days 00:11:22,Id=2:BME680:breathVocEquivalent,22.354300,True,True,2025-10-02 22:58:34,22.556737,-0.043542,11.634652,-0.283675,-0.275444
682,85,0 days 00:11:22,Id=0:BME680:breathVocEquivalent,84.101508,True,False,2025-10-02 22:58:34,84.199075,0.111384,51.603402,2.370060,2.386211

In [13]:
# Split back into dict
dict_of_timeseries = {k: v.drop(columns="keys").reset_index(drop=True) 
             for k, v in timeSeriesData_BIG.groupby("keys")}

In [14]:
#create rolling windows 
window_ranges = [5,15,30,60,120]
for window_size in window_ranges:
    
    column_name = "VOC window " + str(window_size)
    timeSeriesData_BIG[column_name] = np.nan
    for index, row in userInputData.iterrows():
        outer_mask = timeSeriesData_BIG["keys"] == index
        particular_experiment =  timeSeriesData_BIG.loc[outer_mask].copy()
        
        sensors = particular_experiment["sensors"].unique()
    
        for sensor in sensors:
            mask = particular_experiment["sensors"]==sensor
            particular_experiment.loc[mask,column_name] = particular_experiment.loc[mask].rolling(window_size,center=True,min_periods=1)["VOC"].mean() 
            
        timeSeriesData_BIG[outer_mask] = particular_experiment   

#create a huge dataframe to save it 

# Combine into one DataFrame, keeping the dictionary key

# Reset index so the key becomes a column
#timeSeriesData_BIG_rolling_15 = timeSeriesData_BIG.reset_index(level="seconds")

In [15]:

window_ranges = [5,15,30,60,120]
for window_size in window_ranges:
    
    column_name = "VOC window " + str(window_size) 
    column_name_assigned = column_name + " ratio"

    timeSeriesData_BIG[column_name_assigned] = np.nan

    for index, row in userInputData.iterrows():
        column_name = "VOC window " + str(window_size)
    
    
        outer_mask = timeSeriesData_BIG["keys"] == index
        particular_experiment =  timeSeriesData_BIG.loc[outer_mask].copy()
        
        sensors = particular_experiment["sensors"].unique()
    
        for sensor in sensors:
            mask = particular_experiment["sensors"]==sensor
            ratio = (np.abs(particular_experiment.loc[mask,column_name].to_numpy()))/ (np.abs((particular_experiment.loc[mask,"VOC"].to_numpy()) + 1e-10))
            particular_experiment.loc[mask,column_name_assigned]  = ratio
        timeSeriesData_BIG.loc[outer_mask] = particular_experiment

In [16]:
timeSeriesData_BIG

,keys,timestamp,sensors,VOC,after_insertion,original_value,datetime_timestamp,VOC rolling average,VOC gradient,VOC gradient cumsum,VOC standard scaled,VOC rolling average standard scaled,VOC window 5,VOC window 15,VOC window 30,VOC window 60,VOC window 120,VOC window 5 ratio,VOC window 15 ratio,VOC window 30 ratio,VOC window 60 ratio,VOC window 120 ratio
seconds,,,,,,,,,,,,,,,,,,,,,,
0,0,0 days 00:00:00,Id=1:BME680:breathVocEquivalent,1.472127,False,False,2025-07-01 15:27:19,1.477888,0.000436,0.000436,-0.777880,-0.775347,1.470162,1.472813,1.477888,1.483377,1.504311,0.998665,1.000466,1.003914,1.007642,1.021862
0,0,0 days 00:00:00,Id=2:BME680:breathVocEquivalent,1.430472,False,True,2025-07-01 15:27:19,1.460728,0.002113,0.002113,-0.798329,-0.783781,1.434222,1.442255,1.460728,1.492587,1.564157,1.002622,1.008237,1.021151,1.043423,1.093455
1,0,0 days 00:00:01,Id=1:BME680:breathVocEquivalent,1.468931,False,False,2025-07-01 15:27:20,1.478324,0.000326,0.000762,-0.779448,-0.775133,1.470605,1.472912,1.478324,1.483829,1.504923,1.001139,1.002710,1.006394,1.010142,1.024502
1,0,0 days 00:00:01,Id=2:BME680:breathVocEquivalent,1.434283,False,False,2025-07-01 15:27:20,1.462841,0.002084,0.004197,-0.796458,-0.782742,1.435997,1.443823,1.462841,1.494420,1.566456,1.001195,1.006652,1.019911,1.041928,1.092153
2,0,0 days 00:00:02,Id=1:BME680:breathVocEquivalent,1.469428,False,True,2025-07-01 15:27:21,1.478541,0.000201,0.000963,-0.779204,-0.775026,1.471437,1.473305,1.478541,1.484485,1.505412,1.001367,1.002639,1.006202,1.010247,1.024488
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
681,85,0 days 00:11:21,Id=2:BME680:breathVocEquivalent,22.283267,True,False,2025-10-02 22:58:33,22.600279,-0.044358,11.678194,-0.286728,-0.273564,22.269329,22.301201,22.600279,23.543637,24.583148,0.999375,1.000805,1.014226,1.056561,1.103211
681,85,0 days 00:11:21,Id=0:BME680:breathVocEquivalent,84.520770,True,True,2025-10-02 22:58:33,84.087691,0.127830,51.492018,2.388078,2.381402,84.752830,84.657152,84.087691,81.063512,76.289576,1.002746,1.001614,0.994876,0.959096,0.902613
682,85,0 days 00:11:22,Id=1:BME680:breathVocEquivalent,23.429280,True,True,2025-10-02 22:58:34,23.313412,-0.045570,15.720697,-0.237475,-0.242772,23.399740,23.152824,23.313412,23.605105,23.030900,0.998739,0.988200,0.995055,1.007505,0.982996
682,85,0 days 00:11:22,Id=2:BME680:breathVocEquivalent,22.354300,True,True,2025-10-02 22:58:34,22.556737,-0.043542,11.634652,-0.283675,-0.275444,22.290223,22.276225,22.556737,23.472609,24.579669,0.997134,0.996507,1.009056,1.050027,1.099550
682,85,0 days 00:11:22,Id=0:BME680:breathVocEquivalent,84.101508,True,False,2025-10-02 22:58:34,84.199075,0.111384,51.603402,2.370060,2.386211,84.544177,84.755708,84.199075,81.251884,76.372101,1.005264,1.007779,1.001160,0.966117,0.908094

In [17]:
def printDataBasedOnDate(column_to_print,timeSeriesData_BIG,room_other_grouping):
    
    column_names_keys_color_values = {"Id=0:BME680:breathVocEquivalent":"blue","Id=1:BME680:breathVocEquivalent":"orange","Id=2:BME680:breathVocEquivalent":"green"}
 
    
    for group_name,indexes_of_the_group in room_other_grouping.items(): 
    
        data = timeSeriesData_BIG.loc[timeSeriesData_BIG["keys"].isin(indexes_of_the_group),:]  
      # Create relplot
        g = sns.relplot(
            data=data,
            x="seconds",
            y=column_to_print,
            hue="sensors",
            col="keys",        # separate subplot per key
            kind="line",
            col_wrap=3, 
                height=7,    # default = 5
            aspect=1, # width = height × aspect (so 6 × 1.5 = 9 inches wide per subplot
            palette=column_names_keys_color_values,  # <<< ensures the same colors across all subplots  
            linewidth=2,
           facet_kws={
            "sharex": False,
            "sharey": False       
    
        })
        if ("gradient" not in column_to_print) and ("ratio" not in column_to_print):          
            #g.fig.set_size_inches(20, 16)  # width, height for total figure
            # Get the horizontal and  vertical line position for this experiment
            for key_value, ax in g.axes_dict.items():
                for column_name,color in column_names_keys_color_values.items():
        
                # Example: horizontal line from x=100 to x=500
                    ax.hlines(
                        y=userInputData.at[key_value,column_name+" before insertion median"], xmin=0, xmax=userInputData.at[key_value,"timestamp InsertingSource seconds"],
                        colors=color, linestyles="--", linewidth=1
                    )
                    ax.hlines(
                        y=userInputData.at[key_value,column_name+" after insertion median"], xmin=userInputData.at[key_value,"timestamp InsertingSource seconds"], xmax=userInputData.at[key_value,"time taken total"].total_seconds(),
                        colors=color, linestyles="--", linewidth=1
                    )
                    ax.hlines(
                        y=userInputData.at[key_value,column_name+" before insertion median"+"VOC standard scaled"], xmin=0, xmax=userInputData.at[key_value,"timestamp InsertingSource seconds"],
                        colors=color, linestyles=":", linewidth=1
                    )
                    ax.hlines(
                        y=userInputData.at[key_value,column_name+" after insertion median"+"VOC standard scaled"], xmin=userInputData.at[key_value,"timestamp InsertingSource seconds"], xmax=userInputData.at[key_value,"time taken total"].total_seconds(),
                        colors=color, linestyles=":", linewidth=1
                    )
        
                
    # Get the horizontal and  vertical line position for this experiment
        for key_value, ax in g.axes_dict.items():
            for column_name,color in column_names_keys_color_values.items():
                #value to show the time that source is inserted
                vline_x = userInputData.at[key_value, "timestamp InsertingSource seconds"]
                
                ax.axvline(x=vline_x, color="red", linestyle="--", linewidth=2)
                #value to show median in not log scaled and scaled for each sensor
                if ("gradient" not in column_to_print) and ("ratio" not in column_to_print):
                 
                    
                    name=column_name+" before insertion median"
            
                    ax.hlines(
                        y=userInputData.at[key_value,name], xmin=0, xmax=userInputData.at[key_value,"timestamp InsertingSource timedelta"].total_seconds(),
                        colors=color, linestyles="--", linewidth=2
                    )
                    name =column_name+" after insertion median"
                    
                    ax.hlines(
                        y=userInputData.at[key_value,name], xmin=userInputData.at[key_value,"timestamp InsertingSource timedelta"].total_seconds(), xmax=userInputData.at[key_value,"time taken total"].total_seconds(),
                        colors=color, linestyles="--", linewidth=1
                    )
                    
                    name =column_name+" before insertion median"+"VOC standard scaled"
                    
                    ax.hlines(
                        y=userInputData.at[key_value,name], xmin=0, xmax=userInputData.at[key_value,"timestamp InsertingSource timedelta"].total_seconds(),
                        colors=color, linestyles=":", linewidth=2
                    )
                    name =column_name+" after insertion median"+"VOC standard scaled"
                    ax.hlines(
                        y=userInputData.at[key_value,name], xmin=userInputData.at[key_value,"timestamp InsertingSource timedelta"].total_seconds(), xmax=userInputData.at[key_value,"time taken total"].total_seconds(),
                        colors=color, linestyles=":", linewidth=1
                    )
                userInputDataRow = userInputData.loc[key_value,:]
                position = f"front wall:{userInputDataRow['front-wall']},left wall:{userInputDataRow['side-left-wall']},\nright wall:{userInputDataRow['side-right-wall']},back wall:{userInputDataRow['back-wall']} \n"
                condition = f" are-doors-opened:{userInputDataRow['are-doors-opened']},are-people-inside:{userInputDataRow['are-people-inside']},\n"
                condition = condition  + f"are-windows-opened:{userInputDataRow['are-windows-opened']},are-fans-on:{userInputDataRow['are-fans-on']},\n notes:{userInputDataRow['notes']}\n"
                subtitle= f" experimentState:{userInputDataRow['experimentState']}, position: {position} , condition {condition}"
                ax.set_title(subtitle, fontsize=9)   
            g.fig.suptitle(f"Group: {group_name}", fontsize=16)
        
            g.fig.subplots_adjust(
                    top=0.75,   # space for overall title
                    wspace=0.2, # horizontal space between subplots
                    hspace=0.3 # vertical space between subplots
                   )
    
             # Overall title for the figure
        # Titles for each subplot are automatically the 'keys', but you can customize
            
                
    
        #     ax.text(
        #     0.5, 1.05, subtitle,          # x=0.5 center, y=1.05 slightly above plot
        #     transform=ax.transAxes,        # coordinates relative to axes
        #     ha='center',                   # center horizontally
        #     fontsize=10
        # )

In [18]:
room_other_grouping = userInputData.groupby(["date of experiment","room"]).groups

In [ ]:
printDataBasedOnDate("VOC",timeSeriesData_BIG,room_other_grouping)

In [ ]:
printDataBasedOnDate("VOC window 30",timeSeriesData_BIG,room_other_grouping)

In [ ]:
printDataBasedOnDate("VOC rolling average standard scaled",timeSeriesData_BIG,room_other_grouping)

In [ ]:
printDataBasedOnDate("VOC gradient",timeSeriesData_BIG,room_other_grouping)

In [ ]:
printDataBasedOnDate("VOC gradient cumsum",timeSeriesData_BIG,room_other_grouping)

In [ ]:
timeSeriesData_BIG

In [ ]:
grad_ratio_df = pd.DataFrame(index=range(userInputData.shape[0])) 
window_ranges = [5,15,30,60,120]
for window_size in window_ranges:
    
    column_name = "VOC window " + str(window_size)
    timeSeriesData_BIG

    grad_ratio_df[column_name] = np.nan
        
for window_size in window_ranges:
    column_name = "VOC window " + str(window_size)

    for index, row in userInputData.iterrows():
            outer_mask = timeSeriesData_BIG["keys"] == index
            particular_experiment =  timeSeriesData_BIG.loc[outer_mask].copy()
            
            sensors = particular_experiment["sensors"].unique()
            mean =0
            for sensor in sensors:
                column_name_par = column_name + sensor
                mask = particular_experiment["sensors"]==sensor
                grad_ratio = np.abs(particular_experiment.loc[mask,column_name].to_numpy()) / np.abs((particular_experiment.loc[mask,"VOC"].to_numpy()) + 1e-10)
                mean = mean + grad_ratio.mean()
            grad_ratio_df.loc[index,column_name]  =  mean/sensors.shape[0]
        

# Relative change in gradient magnitude

In [ ]:
grad_ratio_df.tail(60)